apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "renovate-bot.fullname" . }}
  labels:
    {{- include "renovate-bot.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "renovate-bot.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "renovate-bot.fullname" . }}
                      key: RENOVATE_TOKEN
                - name: RENOVATE_CONFIG_FILE
                  value: /opt/renovate/config.js
                - name: LOG_LEVEL
                  value: {{ .Values.renovate.logLevel | quote }}
                {{- if .Values.opentelemetry.enabled }}
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: {{ .Values.opentelemetry.endpoint | quote }}
                - name: OTEL_SERVICE_NAME
                  value: {{ .Values.opentelemetry.serviceName | quote }}
                - name: OTEL_SERVICE_NAMESPACE
                  value: {{ .Values.opentelemetry.serviceNamespace | quote }}
                {{- if .Values.opentelemetry.debugConsole }}
                - name: RENOVATE_TRACING_CONSOLE_EXPORTER
                  value: "true"
                {{- end }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/config.js
                  subPath: config.js
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: {{ include "renovate-bot.fullname" . }}
